CREATE TABLE taxi_trip (uuid VARCHAR(50), 
	pickup_datetime VARCHAR(50),
	dropoff_datetime VARCHAR(50),
	store_and_fwd_flag VARCHAR(50), 
	rate_code VARCHAR(50), 
	pickup_longitude DOUBLE, 
	pickup_latitude DOUBLE, 
	dropoff_longitude DOUBLE, 
	dropoff_latitude DOUBLE, 
	passenger_count INT, 
	fare_amount DOUBLE, 
	tip_amount DOUBLE, 
	tolls_amount DOUBLE, 
	total_amount DOUBLE, 
	payment_type VARCHAR(50), 
	distance_between_service INT, 
	time_between_service BIGINT, 
	trip_type VARCHAR(50)														
);
